apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert1
spec:
  selector:
    matchLabels:
      app: alert1
  template:
    metadata:
      labels:
        app: alert1
    spec:
      containers:
      - name: alert1
        image: harishoo7/alert
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        
