apiVersion: apps/v1
kind: Deployment
metadata:
  name: alerts
spec:
  selector:
    matchLabels:
      app: alerts
  template:
    metadata:
      labels:
        app: alerts
    spec:
      containers:
      - name: alerts
        image: harishoo7/alert
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        
